site_name: STS Apv
site_url: https://caspertjuh.github.io/STSAPV/
site_author: Caspertjuh
site_description: >-
  Shady's test server Informatie en APV
# Configuration
theme:
  name: material
  features:
  palette:
    - scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode