import markdown
md = markdown.Markdown(extensions=['pymdownx.keys'])

site_name: STS APV
site_url: https://caspertjuh.github.io/STSAPV/
site_author: Caspertjuh
site_description: >-
  Shady's test server Informatie en APV

# Copyright
copyright: Copyright &copy; 2023 Caspertjuh

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch naar dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch naar light mode
  favicon: assets/favicon.png
  
markdown_extensions:
  - pymdownx.keys
  
# Page tree
nav:
  - Home: index.md
  - Keybinds: keybinds.md
  - Commands: commands.md
  - Wapenlijst: wapenlijst.md
  - Joblijst: joblijst.md
  - Voertuigenlijst: voertuigenlijst.md
  - Itemlijst: itemlijst.md
  - Redzoneinfo: redzoneinfo.md
